# Build web and deploy on master branch
name: build

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: export PUB_CACHE=$PWD/.pub_cache/
      - name: Cache pub modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pub-modules
        with:
          path: |
            $PWD/.pub_cache/
          key: ${{ runner.os }}-flutter
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - name: Print Flutter SDK version
        run: flutter --version
      - name: Get dependencies
        run: flutter pub get
      - name: Codegen
        run: flutter pub run build_runner build --delete-conflicting-outputs --release
      - name: Check sources with analyzer
        run: flutter analyze --no-pub --congratulate --current-package --preamble --write=analyze.txt
      - name: Run tests
        run: flutter test --no-pub --concurrency=6 --platform tester --coverage test/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false
          path_to_write_report: ./coverage/codecov_report.txt
          token: ${{ secrets.CODECOV_TOKEN }}
      #- name: Check Code Coverage
      #  uses: ChicagoFlutter/lcov-cop@v1.0.2
      #  with:
      #    path: coverage/lcov.info
      #    min_coverage: 100
      #    exclude: "**/*.g.dart"
      - name: Enable web
        run: flutter config --enable-web
      - name: Build web
        run: flutter build web --release
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Build apk
        run: flutter build apk --release --no-pub --shrink --target-platform android-arm,android-arm64,android-x64
      - name: Move apk to folder
        run: |
          mkdir -p build/apk
          mv build/app/outputs/apk/release/app-release.apk build/apk/android.apk
      - name: Upload build result for job test
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            coverage/
            analyze.txt
            build/web/
            build/apk/

# TODO: deploy on master
