name: Check common feature branch without build

on:
  push:
    branches-ignore:
      - master
      - main
      - dev
  pull_request:
    branches-ignore:
      - master
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: export PUB_CACHE=$PWD/.pub_cache/
      - name: Cache pub modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pub-modules
        with:
          path: |
            $PWD/.pub_cache/
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('.packages') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-${{ env.cache-name }}
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - name: Print Flutter SDK version
        run: flutter --version
      - name: Get dependencies
        run: flutter pub get
      - name: Codegen
        run: flutter pub run build_runner build --delete-conflicting-outputs --release
      - name: Check sources with analyzer
        run: flutter analyze --no-pub --congratulate --current-package --preamble --write=analyze.txt
      - name: Run tests
        run: flutter test --no-pub --concurrency=6 --platform tester --coverage test/
      - name: Upload build result for job build_web
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            coverage/
            analyze.txt
